spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
    drop-first: true

  mail:
    host: felipebarcellosreis27@gmail.com
    port: 587
    username: felipebarcellosreis27@gmail.com
    password: flp120702
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false

  application:
    mail:
      endereco-remetente: email@email.com
      nome-remetente: SISGESTAR
